# Generated by Django 4.1.3 on 2022-11-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mobile_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
